name: ci.yml

env:
  ONNXRUNTIME_VERSION: 1.29.0

on: [push]

jobs:
  linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++
          mkdir -p /opt/onnxruntime
          curl -fL "https://github.com/microsoft/onnxruntime/releases/download/v$ONNXRUNTIME_VERSION/onnxruntime-linux-x64-$ONNXRUNTIME_VERSION.tgz" -o /tmp/onnxruntime.tgz
          tar -xzf /tmp/onnxruntime.tgz --strip-components=1 -C /opt/onnxruntime 
          rm /tmp/onnxruntime.tgz

      - name: Configure
        run: cmake ./HeightmapGenerator -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build && ./Tests
